# Generated by Django 3.2.4 on 2023-02-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_due_to_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon_Listing',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='amazon_listing', serialize=False, to='inventory_api.item')),
                ('order_id', models.CharField(max_length=200)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField()),
                ('total_amazon_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebay_Listing',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ebay_listing', serialize=False, to='inventory_api.item')),
                ('order_id', models.CharField(max_length=200)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField()),
                ('final_value_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('add_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercari_Listing',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mercari_listing', serialize=False, to='inventory_api.item')),
                ('order_id', models.CharField(max_length=200)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField()),
                ('total_mercari_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poshmark_Listing',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poshmark_listing', serialize=False, to='inventory_api.item')),
                ('order_id', models.CharField(max_length=200)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField()),
                ('total_poshmark_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
